# Generated by Django 6.0.2 on 2026-03-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qari',
            new_name='Reciter',
        ),
        migrations.AlterModelOptions(
            name='reciter',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Reciter', 'verbose_name_plural': "Reciters'"},
        ),
    ]
