# Generated by Django 6.0.2 on 2026-03-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_qari_reciter_alter_reciter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciter',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Reciter', 'verbose_name_plural': 'Reciters'},
        ),
        migrations.RemoveField(
            model_name='reciter',
            name='number',
        ),
    ]
