# Generated by Django 6.0.2 on 2026-04-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reciter_options_remove_reciter_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciter',
            new_name='Biography',
        ),
    ]
