# Generated by Django 6.0.2 on 2026-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_reciter_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City/Country',
                'verbose_name_plural': 'City/Countries',
                'ordering': ['id', 'country', 'city'],
            },
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'ordering': ['id', 'full_name'], 'verbose_name': 'Biography', 'verbose_name_plural': 'Biographies'},
        ),
        migrations.RemoveField(
            model_name='biography',
            name='age',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='authored_books',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='location_of_reading',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='name',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='path',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='readings',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='school',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='source',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='students',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='title',
        ),
        migrations.AddField(
            model_name='biography',
            name='alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_name',
            field=models.CharField(default='default', max_length=300, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
