# Generated by Django 6.0.2 on 2026-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attribute_alter_biography_birthplace_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityCountry',
            new_name='Location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id', 'country', 'city'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
