# Generated by Django 6.0.2 on 2026-04-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_biography_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.RemoveField(
            model_name='biography',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='death_year',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='user',
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_date_approximate',
            field=models.BooleanField(default=False, verbose_name='Birth Date Approximate'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_greg_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Birth Day (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_greg_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Birth Month (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_greg_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Birth Year (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_hijri_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Birth Day (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_hijri_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Birth Month (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_hijri_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Birth Year (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_date_approximate',
            field=models.BooleanField(default=False, verbose_name='Death Date Approximate'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_greg_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Death Day (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_greg_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Death Month (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_greg_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Death Year (Gregorian)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_hijri_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Death Day (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_hijri_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Death Month (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_hijri_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Death Year (Hijri)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='biography',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
