# Generated by Django 6.0.2 on 2026-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_attribute_options_remove_biography_birth_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biography',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='attributes',
        ),
        migrations.AddField(
            model_name='biography',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='biographies', to='core.attribute'),
        ),
    ]
