# Generated by Django 6.0.2 on 2026-04-24 14:55

from django.db import migrations, models


def copy_old_to_ar(apps, schema_editor):
    Biography = apps.get_model('core', 'Biography')
    for obj in Biography.objects.all():
        obj.full_name_ar = obj.full_name
        obj.alias_ar = obj.alias
        obj.save(update_fields=['full_name_ar', 'alias_ar'])

    Location = apps.get_model('core', 'Location')
    seen = set()
    for obj in Location.objects.all():
        obj.city_ar = obj.city
        # Ensure country_ar is unique (append id if duplicate)
        country = obj.country
        if country in seen:
            country = f"{country}_{obj.pk}"
        seen.add(country)
        obj.country_ar = country
        obj.save(update_fields=['city_ar', 'country_ar'])

    Attribute = apps.get_model('core', 'Attribute')
    for obj in Attribute.objects.all():
        obj.short_name_ar = obj.short_name
        obj.long_name_ar = obj.long_name
        obj.description_ar = obj.description
        obj.save(update_fields=['short_name_ar', 'long_name_ar', 'description_ar'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_biography_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['id', 'short_name_ar'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'ordering': ['id', 'full_name_ar'], 'verbose_name': 'Biography', 'verbose_name_plural': 'Biographies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id', 'country_ar', 'city_ar'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),

        # Step 1 — add new bilingual fields (country_ar without unique yet)
        migrations.AddField(
            model_name='biography',
            name='full_name_ar',
            field=models.CharField(default='', max_length=300, verbose_name='Full Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Full Name (English)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='alias_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alias (Arabic)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='alias_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alias (English)'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_ar',
            field=models.CharField(default='', max_length=255, verbose_name='City (Arabic)'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='City (English)'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_ar',
            field=models.CharField(default='', max_length=255, verbose_name='Country (Arabic)'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country (English)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='short_name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='Short Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Name (English)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='long_name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='Long Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='long_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Long Name (English)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),

        # Step 2 — copy existing data into the new _ar fields
        migrations.RunPython(copy_old_to_ar, migrations.RunPython.noop),

        # Step 3 — remove old single-language fields
        migrations.RemoveField(model_name='biography', name='full_name'),
        migrations.RemoveField(model_name='biography', name='alias'),
        migrations.RemoveField(model_name='location', name='city'),
        migrations.RemoveField(model_name='location', name='country'),
        migrations.RemoveField(model_name='attribute', name='short_name'),
        migrations.RemoveField(model_name='attribute', name='long_name'),
        migrations.RemoveField(model_name='attribute', name='description'),

        # Step 4 — now that duplicates are resolved, add unique constraint to country_ar
        migrations.AlterField(
            model_name='location',
            name='country_ar',
            field=models.CharField(max_length=255, unique=True, verbose_name='Country (Arabic)'),
        ),
    ]
