# Generated by Django 6.0.2 on 2026-05-11 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_biography_location_attribute_bilingual_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_biographies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biography',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_biographies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biography',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='long_name_ar',
            field=models.CharField(max_length=255, verbose_name='Long Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='short_name_ar',
            field=models.CharField(max_length=255, verbose_name='Short Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='full_name_ar',
            field=models.CharField(max_length=300, verbose_name='Full Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_ar',
            field=models.CharField(max_length=255, verbose_name='City (Arabic)'),
        ),
        migrations.CreateModel(
            name='TeacherStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_ar', models.CharField(blank=True, max_length=500, verbose_name='Notes (Arabic)')),
                ('notes_en', models.CharField(blank=True, max_length=500, verbose_name='Notes (English)')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relationships', to='core.biography', verbose_name='Student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_relationships', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='core.biography', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher-Student Relationship',
                'verbose_name_plural': 'Teacher-Student Relationships',
                'ordering': ['teacher', 'student'],
                'unique_together': {('teacher', 'student')},
            },
        ),
        migrations.AddField(
            model_name='biography',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='students', through='core.TeacherStudentRelationship', to='core.biography'),
        ),
    ]
