# Generated by Django 6.0.2 on 2026-05-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_biography_last_modified_by_biography_submitted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudentrelationship',
            name='submitted_by',
        ),
    ]
