# Generated by Django 6.0.2 on 2026-05-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_teacherstudentrelationship_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudentrelationship',
            name='published',
        ),
    ]
