# Generated by Django 6.0.2 on 2026-05-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_teacherstudentrelationship_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=500, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Name (English)')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.biography', verbose_name='Biography')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['biography', 'id'],
            },
        ),
    ]
