# Generated by Django 6.0.2 on 2026-05-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_esnadtemplate_esnadtemplatelink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esnadlink',
            unique_together={('esnad', 'narrator')},
        ),
    ]
