# Generated by Django 6.0.2 on 2026-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_esnadlink_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esnadlink',
            unique_together={('esnad', 'narrator'), ('esnad', 'order')},
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country_ar', 'city_ar'), name='unique_location_ar'),
        ),
    ]
