# Generated by Django 6.0.2 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_esnadlink_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_ar',
            field=models.CharField(max_length=255, verbose_name='Country (Arabic)'),
        ),
    ]
