# Generated by Django 6.0.2 on 2026-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_location_country_ar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esnadlink',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='esnadtemplatelink',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudentrelationship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='esnadlink',
            constraint=models.UniqueConstraint(fields=('esnad', 'narrator'), name='unique_esnad_narrator'),
        ),
        migrations.AddConstraint(
            model_name='esnadlink',
            constraint=models.UniqueConstraint(fields=('esnad', 'order'), name='unique_esnad_order'),
        ),
        migrations.AddConstraint(
            model_name='esnadtemplatelink',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_template_order'),
        ),
        migrations.AddConstraint(
            model_name='esnadtemplatelink',
            constraint=models.UniqueConstraint(fields=('template', 'narrator'), name='unique_template_narrator'),
        ),
        migrations.AddConstraint(
            model_name='teacherstudentrelationship',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='unique_teacher_student'),
        ),
    ]
