# Generated by Django 6.0.2 on 2026-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_esnadlink_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='esnadlink',
            name='unique_esnad_order',
        ),
        migrations.RemoveConstraint(
            model_name='esnadtemplatelink',
            name='unique_template_order',
        ),
        migrations.AddField(
            model_name='esnad',
            name='narrators',
            field=models.ManyToManyField(blank=True, related_name='esnads_as_narrator', through='core.EsnadLink', through_fields=('esnad', 'narrator'), to='core.biography', verbose_name='Narrators'),
        ),
        migrations.AlterField(
            model_name='esnadlink',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
