# Generated by Django 6.0.2 on 2026-05-15 11:27

from django.db import migrations, models


def backfill_name_search(apps, schema_editor):
    from core.search import biography_search_text

    Biography = apps.get_model("core", "Biography")
    rows = []
    for bio in Biography.objects.all().only(
        "id", "full_name_ar", "full_name_en", "alias_ar", "alias_en", "name_search",
    ):
        bio.name_search = biography_search_text(
            bio.full_name_ar, bio.full_name_en, bio.alias_ar, bio.alias_en,
        )
        rows.append(bio)
    Biography.objects.bulk_update(rows, ["name_search"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_esnadlink_unique_esnad_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='name_search',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.RunPython(backfill_name_search, migrations.RunPython.noop),
    ]
