# Generated by Django 6.0.2 on 2026-05-14 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_esnadlink_unique_esnad_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='biographies', to='core.attribute', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthplace', to='core.location', verbose_name='Birthplace'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='death_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_location', to='core.location', verbose_name='Death Location'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometown', to='core.location', verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_biographies', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_biographies', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
