# Generated by Django 6.0.2 on 2026-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_renumber_esnadlink_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='comments_ar',
            field=models.TextField(blank=True, verbose_name='Comments (Arabic)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='comments_en',
            field=models.TextField(blank=True, verbose_name='Comments (English)'),
        ),
    ]
