# Generated by Django 6.0.2 on 2026-06-05 12:38

from django.db import migrations, models


def backfill_per_calendar_flags(apps, schema_editor):
    """Set each new per-calendar approximate flag from existing row data.

    Rule: a side is approximate iff the user did not supply a full
    year+month+day on that side (covers year-only, year+month, and fully
    derived sides).
    """
    Biography = apps.get_model("core", "Biography")
    rows = []
    for bio in Biography.objects.all().only(
        "id",
        "birth_hijri_year", "birth_hijri_month", "birth_hijri_day",
        "birth_greg_year", "birth_greg_month", "birth_greg_day",
        "death_hijri_year", "death_hijri_month", "death_hijri_day",
        "death_greg_year", "death_greg_month", "death_greg_day",
    ):
        bio.birth_hijri_approximate = not (
            bio.birth_hijri_year and bio.birth_hijri_month and bio.birth_hijri_day
        )
        bio.birth_greg_approximate = not (
            bio.birth_greg_year and bio.birth_greg_month and bio.birth_greg_day
        )
        bio.death_hijri_approximate = not (
            bio.death_hijri_year and bio.death_hijri_month and bio.death_hijri_day
        )
        bio.death_greg_approximate = not (
            bio.death_greg_year and bio.death_greg_month and bio.death_greg_day
        )
        rows.append(bio)
    if rows:
        Biography.objects.bulk_update(
            rows,
            [
                "birth_hijri_approximate", "birth_greg_approximate",
                "death_hijri_approximate", "death_greg_approximate",
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_biography_comments_ar_biography_comments_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='birth_hijri_approximate',
            field=models.BooleanField(default=False, verbose_name='Birth Hijri Approximate'),
        ),
        migrations.AddField(
            model_name='biography',
            name='birth_greg_approximate',
            field=models.BooleanField(default=False, verbose_name='Birth Gregorian Approximate'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_hijri_approximate',
            field=models.BooleanField(default=False, verbose_name='Death Hijri Approximate'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_greg_approximate',
            field=models.BooleanField(default=False, verbose_name='Death Gregorian Approximate'),
        ),
        migrations.RunPython(backfill_per_calendar_flags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='biography',
            name='birth_date_approximate',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='death_date_approximate',
        ),
    ]
