# Generated by Django 6.0.2 on 2026-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_split_date_approximate_per_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name_ar', models.CharField(max_length=255, verbose_name='Short Name (Arabic)')),
                ('short_name_en', models.CharField(blank=True, max_length=255, verbose_name='Short Name (English)')),
                ('long_name_ar', models.CharField(blank=True, max_length=255, verbose_name='Long Name (Arabic)')),
                ('long_name_en', models.CharField(blank=True, max_length=255, verbose_name='Long Name (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['id', 'short_name_ar'],
            },
        ),
        migrations.RemoveField(
            model_name='teacherstudentrelationship',
            name='notes_ar',
        ),
        migrations.RemoveField(
            model_name='teacherstudentrelationship',
            name='notes_en',
        ),
        migrations.AddField(
            model_name='teacherstudentrelationship',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='relationships', to='core.note', verbose_name='Notes'),
        ),
    ]
