# Generated by Django 6.0.2 on 2026-06-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_note_remove_teacherstudentrelationship_notes_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description_en',
        ),
    ]
