# Generated by Django 6.0.2 on 2026-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_note_to_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='description_ar',
            field=models.CharField(max_length=255, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description (English)'),
        ),
    ]
