# Generated by Django 6.0.2 on 2026-06-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_reading_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esnad',
            options={'ordering': ['biography', 'id'], 'verbose_name': 'Esnad', 'verbose_name_plural': 'Transmission Chains'},
        ),
        migrations.AddField(
            model_name='biography',
            name='is_female',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
    ]
