# Generated by Django 6.0.2 on 2026-06-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_biography_is_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
