# Generated by Django 6.0.2 on 2026-06-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_biography_image_featured_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='featured_summary_ar',
            field=models.TextField(blank=True, help_text='نبذة مختصرة تظهر في قسم أبرز التراجم في الصفحة الرئيسية', verbose_name='Featured Summary (Arabic)'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='featured_summary_en',
            field=models.TextField(blank=True, help_text='Short summary shown in the Featured Biographies card on the home page', verbose_name='Featured Summary (English)'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for Featured Biographies in the home page', null=True, upload_to='biography/images', verbose_name='Image'),
        ),
    ]
