# Generated by Django 6.0.2 on 2026-06-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_biography_featured_summary_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='birth_date_raw_ar',
            field=models.CharField(blank=True, default='', help_text='النص الأصلي لتاريخ الميلاد كما ورد في مصدر الاستيراد', max_length=255, verbose_name='Birth Date (raw Arabic text)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='death_date_raw_ar',
            field=models.CharField(blank=True, default='', help_text='النص الأصلي لتاريخ الوفاة كما ورد في مصدر الاستيراد', max_length=255, verbose_name='Death Date (raw Arabic text)'),
        ),
    ]
