# Generated by Django 6.0.2 on 2026-02-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name (alt text)')),
                ('logo', models.ImageField(upload_to='landing/clients', verbose_name='Logo')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/blog', verbose_name='Image')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('url', models.URLField(blank=True, verbose_name='Link')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Featured post',
                'verbose_name_plural': 'Featured posts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Column title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Footer column',
                'verbose_name_plural': 'Footer columns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='Subtitle (Arabic)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Subtitle (English)')),
                ('button_text_ar', models.CharField(default='اكتشف المزيد', max_length=100, verbose_name='Button text (Arabic)')),
                ('button_text_en', models.CharField(default='Explore more', max_length=100, verbose_name='Button text (English)')),
                ('button_link', models.CharField(default='#welcome', max_length=500, verbose_name='Button link (URL or #anchor)')),
                ('video_url', models.CharField(blank=True, help_text="e.g. path under static like 'video/quran_video.mp4' or full URL", max_length=500, verbose_name='Video URL or path')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/hero', verbose_name='Image (if no video)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('welcome', 'Welcome'), ('services', 'Services'), ('blog', 'Blog'), ('clients', 'Clients'), ('team', 'Team')], unique=True)),
                ('heading_ar', models.CharField(max_length=255, verbose_name='Heading (Arabic)')),
                ('heading_en', models.CharField(max_length=255, verbose_name='Heading (English)')),
                ('lead_ar', models.CharField(blank=True, max_length=500, verbose_name='Lead / subtitle (Arabic)')),
                ('lead_en', models.CharField(blank=True, max_length=500, verbose_name='Lead / subtitle (English)')),
            ],
            options={
                'verbose_name': 'Landing section',
                'verbose_name_plural': 'Landing sections',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='e.g. fa fa-book, fa fa-clipboard-check', max_length=100, verbose_name='Icon class (FontAwesome)')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('description_ar', models.CharField(blank=True, max_length=500, verbose_name='Description (Arabic)')),
                ('description_en', models.CharField(blank=True, max_length=500, verbose_name='Description (English)')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(default='المركز العالمي لتاريخ ووثائق القرآء', max_length=255, verbose_name='Site name (Arabic)')),
                ('site_name_en', models.CharField(default='The International Center for the History and Documentation of Quran Reciters', max_length=255, verbose_name='Site name (English)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/logo', verbose_name='Logo')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='landing/logo', verbose_name='Logo (dark)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='landing/favicon', verbose_name='Favicon')),
                ('footer_title_ar', models.CharField(blank=True, max_length=255, verbose_name='Footer title (Arabic)')),
                ('footer_title_en', models.CharField(blank=True, max_length=255, verbose_name='Footer title (English)')),
                ('footer_description_ar', models.TextField(blank=True, verbose_name='Footer description (Arabic)')),
                ('footer_description_en', models.TextField(blank=True, verbose_name='Footer description (English)')),
                ('footer_button_text_ar', models.CharField(default='سجّل الآن', max_length=100, verbose_name='Footer button (Arabic)')),
                ('footer_button_text_en', models.CharField(default='Register Now', max_length=100, verbose_name='Footer button (English)')),
                ('footer_button_link', models.URLField(blank=True, verbose_name='Footer button URL')),
                ('copyright_ar', models.CharField(default='المركز العالمي لتاريخ ووثائق القرآء. جميع الحقوق محفوظة.', max_length=255, verbose_name='Copyright (Arabic)')),
                ('copyright_en', models.CharField(default='The International Center for the History and Documentation of Quran Reciters. All rights reserved.', max_length=255, verbose_name='Copyright (English)')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='e.g. fa fa-3x fa-book', max_length=100, verbose_name='Icon class (FontAwesome)')),
                ('value_from', models.PositiveIntegerField(default=0, verbose_name='Animate from')),
                ('value_to', models.PositiveIntegerField(verbose_name='Value to display')),
                ('label_ar', models.CharField(max_length=255, verbose_name='Label (Arabic)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Label (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Stat counter',
                'verbose_name_plural': 'Stat counters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(max_length=255, verbose_name='Role / title')),
                ('bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/team', verbose_name='Photo')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_ar', models.CharField(max_length=255, verbose_name='Heading (Arabic)')),
                ('heading_en', models.CharField(max_length=255, verbose_name='Heading (English)')),
                ('lead_ar', models.CharField(blank=True, max_length=500, verbose_name='Lead (Arabic)')),
                ('lead_en', models.CharField(blank=True, max_length=500, verbose_name='Lead (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/welcome', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Welcome section',
                'verbose_name_plural': 'Welcome section',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='landing.footercolumn')),
            ],
            options={
                'verbose_name': 'Footer link',
                'verbose_name_plural': 'Footer links',
                'ordering': ['order'],
            },
        ),
    ]
