# Generated by Django 6.0.2 on 2026-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_featuredpost_bilingual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='excerpt_ar',
            field=models.TextField(blank=True, verbose_name='Excerpt (Arabic)'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Excerpt (English)'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='title_ar',
            field=models.CharField(max_length=255, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (English)'),
        ),
    ]
