# Generated by Django 6.0.2 on 2026-02-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_featuredpost_excerpt_ar_and_more'),
        ('landing', '0004_featuredpost_category_bilingual'),
    ]

    operations = [
    ]
