# Generated by Django 6.0.2 on 2026-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_merge_20260224_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingsection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Column title (Arabic)'),
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Column title (English)'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='label_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Label (Arabic)'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Label (English)'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='category_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category (Arabic)'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category (English)'),
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='title',
            field=models.CharField(blank=True, help_text='Fallback if Arabic/English not set', max_length=100, verbose_name='Column title (legacy)'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='label',
            field=models.CharField(blank=True, help_text='Fallback if Arabic/English not set', max_length=255, verbose_name='Label (legacy)'),
        ),
    ]
