# Generated by Django 6.0.2 on 2026-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_landingsection_options_footercolumn_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='services_description_ar',
            field=models.TextField(blank=True, verbose_name='Services description (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_description_en',
            field=models.TextField(blank=True, verbose_name='Services description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_overline_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services overline (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_overline_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services overline (English)'),
        ),
    ]
