# Generated by Django 6.0.2 on 2026-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_sitesettings_services_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_button_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_button_text_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_button_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_description_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_title_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_overline_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_overline_en',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_ar',
            field=models.TextField(blank=True, max_length=2000, verbose_name='About us description (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='About us description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='About us heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='About us heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/about', verbose_name='About us image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='About us subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='About us subheading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_description_ar',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Blog description (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Blog description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blog heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blog heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blog subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blog subheading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_description_ar',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Contact description (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Contact description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact subheading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_button_link',
            field=models.URLField(blank=True, verbose_name='Donate button URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_button_text_ar',
            field=models.CharField(default='تبرّع الآن', max_length=100, verbose_name='Donate button (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_button_text_en',
            field=models.CharField(default='Donate Now', max_length=100, verbose_name='Donate button (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Donate heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Donate heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Donate subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Donate subheading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Services subheading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='services_description_ar',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Services description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='services_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Services description (English)'),
        ),
    ]
