# Generated by Django 6.0.2 on 2026-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_remove_sitesettings_footer_button_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='column',
        ),
        migrations.DeleteModel(
            name='LandingSection',
        ),
        migrations.DeleteModel(
            name='StatCounter',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='WelcomeSection',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Arabic)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle (English)'),
        ),
        migrations.DeleteModel(
            name='FooterColumn',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
