# Generated by Django 6.0.2 on 2026-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_delete_client_remove_footerlink_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='show_searchbar',
            field=models.BooleanField(default=True, verbose_name='Show search bar'),
        ),
    ]
