# Generated by Django 6.0.2 on 2026-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_heroslide_show_searchbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact address (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact address (English)'),
        ),
    ]
