# Generated by Django 6.0.2 on 2026-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_remove_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_url',
            field=models.URLField(blank=True, verbose_name='About us URL'),
        ),
    ]
