# Generated by Django 6.0.2 on 2026-06-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_sitesettings_about_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'verbose_name': 'Hero section', 'verbose_name_plural': 'Hero section'},
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='order',
        ),
    ]
