# Generated by Django 6.0.2 on 2026-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_heroslide_options_remove_heroslide_button_link_and_more'),
    ]

    operations = [
        # Rename FeaturedPost -> Post (preserves existing rows)
        migrations.RenameModel(
            old_name='FeaturedPost',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        # Drop the old URL field
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        # New fields
        migrations.AddField(
            model_name='post',
            name='body_ar',
            field=models.TextField(blank=True, verbose_name='Body (Arabic)'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Body (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_as_featured',
            field=models.BooleanField(default=False, verbose_name='Show as featured post'),
        ),
    ]
