# Generated by Django 6.0.2 on 2026-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_sitesettings_search_results_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author (Arabic)'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_role_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author role (Arabic)'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_role_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author role (English)'),
        ),
    ]
