# Generated by Django 6.0.2 on 2026-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_post_author_ar_post_author_en_post_author_role_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_dark',
            field=models.ImageField(blank=True, null=True, upload_to='landing/favicon', verbose_name='Favicon (dark)'),
        ),
    ]
