# Generated by Django 6.0.2 on 2026-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_add_favicon_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_description_ar',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Featured biographies description (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Featured biographies description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_heading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Featured biographies heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_heading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Featured biographies heading (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_subheading_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Featured biographies subheading (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_biographies_subheading_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Featured biographies subheading (English)'),
        ),
    ]
